import React from "react";
import type { Metadata } from "next";
import Link from "next/link";
import JsonLd from "../../components/JsonLd";
import { breadcrumbSchema } from "../../lib/jsonld";
import { getLogEntries } from "../../lib/log";

export const metadata: Metadata = {
  title: "Build Log — Written by an Agent",
  description:
    "A weekly changelog of real work across the totalaudiopromo ecosystem, written automatically by a Claude agent from actual commit data.",
  alternates: { canonical: "/log" },
  openGraph: {
    title: "Build Log — Chris Schofield",
    description: "Weekly changelog written by an agent from real commits.",
    url: "/log",
  },
};

export default function LogPage() {
  const entries = getLogEntries();

  return (
    <div className="bg-tap-bg text-tap-text min-h-screen font-sans antialiased">
      <JsonLd
        data={[
          breadcrumbSchema([
            { name: "Home", path: "/" },
            { name: "Build Log", path: "/log" },
          ]),
        ]}
      />
      <section className="py-20 max-w-3xl mx-auto px-6">
        <div className="mb-14">
          <div className="inline-block font-mono text-[9px] uppercase tracking-widest bg-neutral-900 text-white px-2 py-0.5 font-bold mb-3">
            [ BUILD LOG // SELF-WRITING ]
          </div>
          <h1 className="font-serif text-4xl md:text-5xl font-bold tracking-tight text-neutral-950 mb-3">
            Build Log
          </h1>
          <p className="text-tap-text-secondary text-sm leading-relaxed max-w-xl">
            Every Monday, an agent fetches the week&apos;s real commits across the{" "}
            <a
              href="https://github.com/totalaudiopromo"
              target="_blank"
              rel="noopener"
              className="font-bold text-tap-raspberry hover:underline"
            >
              totalaudiopromo
            </a>{" "}
            org, summarizes them with a strict no-invention prompt, and commits the entry back
            to this site — which redeploys itself. No CMS, no database.{" "}
            <a
              href="https://github.com/totalaudiopromo/chrisscho.uk/blob/main/.github/workflows/build-log.yml"
              target="_blank"
              rel="noopener"
              className="font-bold text-tap-raspberry hover:underline"
            >
              Read the workflow ↗
            </a>{" "}
            or{" "}
            <Link href="/writing/how-this-site-writes-its-own-changelog" className="font-bold text-tap-raspberry hover:underline">
              the write-up
            </Link>
            .
          </p>
        </div>

        <div className="space-y-8">
          {entries.map((entry) => (
            <article
              key={entry.week}
              className="border-2 border-neutral-900 bg-white shadow-[4px_4px_0px_rgba(0,0,0,1)]"
            >
              <header className="flex flex-wrap justify-between items-center gap-2 border-b-2 border-neutral-900 px-5 py-3 font-mono text-[10px] uppercase tracking-widest font-bold">
                <span className="bg-tap-raspberry text-white px-2 py-0.5">{entry.week}</span>
                <span className="text-neutral-500">{entry.dateRange}</span>
                <span className="text-neutral-500">
                  {entry.commitCount} commits · {entry.reposTouched.length}{" "}
                  {entry.reposTouched.length === 1 ? "repo" : "repos"}
                </span>
              </header>

              <div className="p-5">
                <p className="text-sm leading-relaxed text-[#44403c] mb-4">{entry.summary}</p>
                <ul className="space-y-2">
                  {entry.highlights.map((highlight) => (
                    <li key={highlight.text} className="text-xs flex items-start gap-2 font-sans">
                      <span className="font-mono text-[9px] font-bold uppercase tracking-wider text-tap-accent shrink-0 mt-0.5 border border-neutral-300 px-1.5 py-0.5 bg-neutral-50">
                        {highlight.repo}
                      </span>
                      <span className="text-neutral-700 leading-relaxed">{highlight.text}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <footer className="border-t border-neutral-200 px-5 py-2 font-mono text-[9px] text-neutral-400">
                generated by {entry.generatedBy}
              </footer>
            </article>
          ))}
        </div>
      </section>
    </div>
  );
}
